FROM node:iron-bookworm-slim

ARG USEROVO_PLUGINS=mobile,web,desktop,plugins,density,locale,browser,sources,views,logger,systemlogs,populator,reports,crashes,push,star-rating,slipping-away-users,compare,server-stats,dbviewer,times-of-day,compliance-hub,alerts,onboarding,consolidate,remote-config,hooks,dashboards,sdk,data-manager,guides
# Userovo Enterprise:
#ARG USEROVO_PLUGINS=mobile,web,desktop,plugins,density,locale,browser,sources,views,license,drill,funnels,retention_segments,flows,cohorts,surveys,remote-config,ab-testing,formulas,activity-map,concurrent_users,revenue,logger,systemlogs,populator,reports,crashes,push,geo,block,users,star-rating,slipping-away-users,compare,server-stats,dbviewer,crash_symbolication,crashes-jira,groups,white-labeling,alerts,times-of-day,compliance-hub,onboarding,active_users,performance-monitoring,config-transfer,consolidate,data-manager,hooks,dashboards,heatmaps,sdk,guides,journey_engine,content

ARG GEOIP=empty
EXPOSE 3001
HEALTHCHECK --start-period=400s CMD bash -c '\
  if [ "$USEROVO_CONFIG_API_API_SSL_ENABLED" = "true" ] || [ "$USEROVO_CONFIG_API_API_SSL_ENABLED" = "\"true\"" ]; then \
    curl -k --fail https://localhost:3001/o/ping || exit 1; \
  else \
    curl --fail http://localhost:3001/o/ping || exit 1; \
  fi'

USER root

# Core dependencies
## Tini
ENV USEROVO_CONTAINER="api" \
	USEROVO_DEFAULT_PLUGINS="${USEROVO_PLUGINS}" \
	USEROVO_CONFIG_API_API_WORKERS="1" \
	USEROVO_CONFIG_API_API_HOST="0.0.0.0" \
	NODE_OPTIONS="--max-old-space-size=2048" \
	TINI_VERSION="0.18.0"\
	PUPPETEER_CACHE_DIR=/opt/userovo/.cache/puppeteer
	
WORKDIR /opt/userovo
COPY . .

# install required dependencies which slim image doesn't have
RUN apt-get update && \
	apt-get install -y iputils-ping procps net-tools telnet apt-transport-https curl wget git make gcc g++ unzip xz-utils

RUN apt-get update && \
	apt-get upgrade -y && \
	cd /usr/src && \
	wget https://www.python.org/ftp/python/3.8.20/Python-3.8.20.tar.xz && \
	tar -xf Python-3.8.20.tar.xz && \
	apt-get install -y build-essential sudo zlib1g-dev libssl3 libncurses5-dev libgdbm-dev libnss3-dev libssl-dev libsqlite3-dev libreadline-dev libffi-dev curl libbz2-dev && \
	cd Python-3.8.20 && \
	./configure --enable-optimizations --enable-shared && \
	make && \
	make altinstall && \
	ldconfig /usr/src/Python-3.8.20 && \
	ln -sf /usr/local/bin/python3.8 /usr/bin/python3

RUN curl -s -L -o /tmp/tini.deb "https://github.com/krallin/tini/releases/download/v${TINI_VERSION}/tini_${TINI_VERSION}.deb" && \
	dpkg -i /tmp/tini.deb && \
	\
	# modify standard distribution
	apt-get update && apt-get install -y sqlite3 && \
	./bin/docker/modify.sh && \
	\
	# preinstall
	cp -n ./api/config.sample.js ./api/config.js && \
	cp -n ./frontend/express/config.sample.js ./frontend/express/config.js && \
	HOME=/tmp npm install -g npm@10 && \
	HOME=/tmp npm install --unsafe-perm=true --allow-root && \
	HOME=/tmp npm install argon2 --build-from-source --unsafe-perm=true --allow-root && \
	./bin/docker/preinstall.sh && \
	bash /opt/userovo/bin/scripts/detect.init.sh && \
        python3.8 -m pip install --upgrade pip setuptools && \
	\
	# cleanup & chown
	npm remove -y --no-save mocha nyc should supertest && \
        apt-get purge -y python3 python3-pip python3-distutils python3-setuptools && \
	apt-get remove -y git gcc g++ make automake autoconf libtool pkg-config unzip sqlite3 wget && \
	apt-get install -y libgbm-dev libgbm1 gconf-service libasound2 libatk1.0-0 libatk-bridge2.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils && \
	apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* && \
        apt-get autoremove -y && \
	rm -rf test /tmp/* /tmp/.??* /var/tmp/* /var/tmp/.??* /var/log/* /root/.npm /usr/local/lib/python3.8/ensurepip/_bundled/*.whl /usr/src/Python* /var/lib/dpkg/info/python3* && \
	\
	# temporary to remove npm bug message
	mkdir /.npm && chown -R 1001:0 /.npm && \
	\
	# More tests needed
	# (find / -perm +6000 -type f -exec chmod a-s {} \; || true) && \
	chown -R 1001:0 /opt/userovo && \
	chmod -R g=u /opt/userovo


USER 1001:0

ENTRYPOINT ["/usr/bin/tini", "-v", "--"]

CMD ["/opt/userovo/bin/docker/cmd.sh"]
