apiVersion: v1
kind: Secret
metadata:
  name: userovo-tls
data:
  tls.crt: YOUR_SSL_CERT_IN_BASE64      # cat cert.crt | base64
  tls.key: YOUR_SSL_KEY_IN_BASE64       # cat cert.key | base64
type: kubernetes.io/tls
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: userovo-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.global-static-ip-name: "userovo-static-ip"
spec:
  tls:
  - hosts:
    - YOUR_HOSTNAME                     # userovo.example.com
    secretName: userovo-tls
  rules:
  - http:
      paths:
      - path: /i
        backend:
          serviceName: userovo-api
          servicePort: 3001
      - path: /i/*
        backend:
          serviceName: userovo-api
          servicePort: 3001
      - path: /o
        backend:
          serviceName: userovo-api
          servicePort: 3001
      - path: /o/*
        backend:
          serviceName: userovo-api
          servicePort: 3001
      - path: /*
        backend:
          serviceName: userovo-frontend
          servicePort: 6001
